services:
  healenium:
    image: healenium/hlm-backend:3.4.0
    ports:
      - "7878:7878"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/healenium?currentSchema=healenium
      - spring.datasource.username=healenium_user
      - spring.datasource.password=YpuMKPC9hVSe
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YpuMKPC9hVSe
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql